name = "Runic"
uuid = "62bfec6d-59d7-401d-8490-b29ee721c001"
version = "1.4.6"

[deps]
JuliaSyntax = "70703baa-626e-46a2-a12c-08ffd08c73b4"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"

[apps]
runic = {}

[compat]
JuliaSyntax = "0.4.10"
Preferences = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
